Add Jackson 2 API test dependency
The most recent release of the plugin (378.v2a_19e1f46c93) fails the
testComprehensivePipelineDescription  test in the plugin BOM.

The test first arrived in the most recent release.

The failure message in the plugin BOM is:

java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
	at org.jenkinsci.plugins.JiraTestResultReporter.AdfFieldConverterTest.testComprehensivePipelineDescription(AdfFieldConverterTest.java:511)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)

The test code includes a dependency on the Jackson 2 API plugin, but
the dependency is not declared in the pom file.  When running in the
development environment, that dependency is provided through a transitive
dependency from the JUnit plugin.  In the plugin BOM, there is an issue
that causes the transitive dependency to not be resolved.

I don't understand the difference between the plugin BOM test execution
context and the plugin repository context well enough to explain the root
of the issue, but I think that it is simple to add a test dependency
on the Jackson 2 API plugin.  The test dependency does not alter the
compile time dependencies of the plugin and does not create a runtime
dependency on the Jackson 2 API plugin.

The test failure can be seen in the plugin BOM repository with the command:

PLUGINS=JiraTestResultReporter TEST=AdfFieldConverterTest LINE=weekly bash ./local-test.sh

Testing done:

* Confirmed that automated tests pass before and after this change with

  mvn -Djenkins.version=2.567 clean verify

I was unable to use the local incremental build of the plugin to confirm
that it runs in the plugin BOM because the failing test requires that
the most recent commit in the incremental build of the plugin must come
from the upstream repository, not from a fork of the upstream repository.